baseURL = 'https://cendralia.com/'
languageCode = 'fr-CA'
title = 'Cendralia'
theme = 'cendralia'
summaryLength = 10

[taxonomy]
tag= "tags"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

